name: CD - Deploy

on:
  workflow_run:
    workflows: ["CI - Build"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code (needed for flyctl)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Download backend artifact
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend
          path: ./server/api/publish

      # 3. Install flyctl
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      # 4. Fly.io deploy
      - name: Fly.io Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd server/api/publish
          fly deploy --remote-only
