# Continuous Integration Workflow 
name: CI (Client + Server)

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:

  client:
    name: Build & Test Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Client Dependencies
        working-directory: client
        run: npm install
      
      - name: Install Jotai
        working-directory: client
        run: npm i jotai

      - name: Build Client
        working-directory: client
        run: npm run build

      - name: Test Client
        working-directory: client
        run: npm test

  server:
    name: Build & Test Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker (For Testcontainers)
        run: |
          sudo systemctl start docker
          docker ps

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      - name: Restore Server Dependencies
        working-directory: server
        run: dotnet restore

      - name: Build Server
        working-directory: server
        run: dotnet build --configuration Release --no-restore

      - name: Test Server
        working-directory: server
        env:
          DOTNET_NOLOGO: true
        run: dotnet test --configuration Release --no-build --verbosity normal